version: "3.3"

services:
  postgres:
    image: postgres:14.2-alpine
    container_name: reservation-postgres
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    restart: always
